default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:
  prepared_statements: false

development:
  <<: *default
  database: ecommerce_deck_development

test:
  <<: *default
  database: ecommerce_deck__test

staging:
  <<: *default
  database: ecommerce_deck__staging

production:
  <<: *default
  database: ecommerce_deck_production
