default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:
  prepared_statements: false

development:
  <<: *default
  database: ecommerce_deck_one_development

test:
  <<: *default
  database: ecommerce_deck_one_test

staging:
  <<: *default
  database: ecommerce_deck_staging

production:
  <<: *default
  database: ecommerce_deck_production
